#!/bin/bash

# Source common functions
# Assume common_functions.sh is in the same directory or made available on the new node
if [ -f ./common_functions.sh ]; then
  source ./common_functions.sh
else
  echo -e "${RED}ERROR: common_functions.sh not found. Please ensure it's available.${NC}"
  exit 1
fi

echo -e "${CYAN}=== Elasticsearch - Add New Node to Cluster Script ===${NC}"
echo "This script will add a new Elasticsearch node to an existing cluster."

# --- User Input & Configuration ---
ELK_VARS_FILE="elk_vars.conf" # Path to elk_vars if transferred to new node
LOADED_ELASTIC_VERSION=""
LOADED_SUPERUSER_USERNAME=""
LOADED_SUPERUSER_PASSWORD=""

if [ -f "${ELK_VARS_FILE}" ]; then
  echo -e "${YELLOW}Found ${ELK_VARS_FILE}. Attempting to load variables...${NC}"
  source "${ELK_VARS_FILE}"
  LOADED_ELASTIC_VERSION="${ELASTIC_VERSION}" # Capture from file
  LOADED_SUPERUSER_USERNAME="${SUPERUSER_USERNAME}"
  LOADED_SUPERUSER_PASSWORD="${SUPERUSER_PASSWORD}"
  echo -e "${GREEN}Variables from ${ELK_VARS_FILE} loaded (if they were set).${NC}"
else
  echo -e "${INFO}${ELK_VARS_FILE} not found. Will prompt for all required values.${NC}"
fi

while true; do
  read -p "Enter the IP address for this new Elasticsearch node: " ELASTIC_HOST_IP
  if validate_ip "${ELASTIC_HOST_IP}"; then
    break
  else
    echo -e "${RED}Invalid IP address format. Please try again.${NC}"
  fi
done

read -p "Enter a unique name for this new Elasticsearch node (e.g., es-node-2): " NODE_NAME
if [ -z "${NODE_NAME}" ]; then
  echo -e "${RED}Node name cannot be empty. Exiting.${NC}"
  exit 1
fi

if [ -n "${LOADED_ELASTIC_VERSION}" ]; then
  read -p "Enter Elasticsearch Version [Default: ${LOADED_ELASTIC_VERSION}]: " ELASTIC_VERSION_INPUT
  ELASTIC_VERSION=${ELASTIC_VERSION_INPUT:-$LOADED_ELASTIC_VERSION}
else
  read -p "Enter Elasticsearch Version (e.g., 8.10.4): " ELASTIC_VERSION
fi
if [ -z "${ELASTIC_VERSION}" ]; then
  echo -e "${RED}Elasticsearch version cannot be empty. Exiting.${NC}"
  exit 1
fi

while true; do
  read -p "Enter the IP address of an existing master-eligible node in the cluster: " FIRST_NODE_IP_FOR_CLUSTER_INFO
  if validate_ip "${FIRST_NODE_IP_FOR_CLUSTER_INFO}"; then
    break
  else
    echo -e "${RED}Invalid IP address format for existing node. Please try again.${NC}"
  fi
done

if [ -n "${LOADED_SUPERUSER_USERNAME}" ]; then
  read -p "Enter Elasticsearch Superuser Username for cluster communication [Default: ${LOADED_SUPERUSER_USERNAME}]: " SUPERUSER_USERNAME_INPUT
  SUPERUSER_USERNAME=${SUPERUSER_USERNAME_INPUT:-$LOADED_SUPERUSER_USERNAME}
else
  read -p "Enter Elasticsearch Superuser Username for cluster communication: " SUPERUSER_USERNAME
fi
if [ -z "${SUPERUSER_USERNAME}" ]; then
  echo -e "${RED}Superuser username cannot be empty. Exiting.${NC}"
  exit 1
fi

if [ -n "${LOADED_SUPERUSER_PASSWORD}" ]; then
  read -s -p "Enter Elasticsearch Superuser Password for cluster communication [Press Enter to use stored if available, or type new]: " SUPERUSER_PASSWORD_INPUT
  echo
  SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD_INPUT:-$LOADED_SUPERUSER_PASSWORD}
else
  read -s -p "Enter Elasticsearch Superuser Password for cluster communication: " SUPERUSER_PASSWORD
  echo
fi
if [ -z "${SUPERUSER_PASSWORD}" ]; then
  echo -e "${RED}Superuser password cannot be empty. Exiting.${NC}"
  exit 1
fi

read -p "Enter the Enrollment Token generated by the first Elasticsearch node: " ENROLLMENT_TOKEN
if [ -z "${ENROLLMENT_TOKEN}" ]; then
  echo -e "${RED}Enrollment token cannot be empty. Exiting.${NC}"
  exit 1
fi

# --- Prerequisites ---
echo -e "${YELLOW}Installing prerequisite packages...${NC}"
install_prerequisites


# --- Elasticsearch Installation ---
echo -e "${YELLOW}Adding Elastic APT repository...${NC}"
progress_bar 2 "Adding Elastic GPG Key & Repository..."
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/${ELASTIC_VERSION%.*}.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-${ELASTIC_VERSION%.*}.x.list
echo -e "${GREEN}Elastic APT repository added.${NC}"

echo -e "${YELLOW}Updating package lists and installing Elasticsearch ${ELASTIC_VERSION}...${NC}"
sudo apt-get update > /dev/null 2>&1
progress_bar 10 "Installing Elasticsearch (version ${ELASTIC_VERSION})... This may take a few minutes."
if sudo apt-get install -y "elasticsearch=${ELASTIC_VERSION}"; then
  echo -e "${GREEN}Elasticsearch ${ELASTIC_VERSION} installed successfully.${NC}"
else
  echo -e "${RED}Failed to install Elasticsearch ${ELASTIC_VERSION}. Please check the version and APT configuration.${NC}"
  exit 1
fi

# --- Cluster Joining and Configuration ---
echo -e "${YELLOW}Fetching cluster name from existing node ${FIRST_NODE_IP_FOR_CLUSTER_INFO}...${NC}"
# Using -k (insecure) for this call as the node doesn't have cluster CA yet.
# The primary purpose is to get the cluster name. Secure join is handled by reconfigure-node.
CLUSTER_HEALTH_RESPONSE=$(curl -k -s -u "${SUPERUSER_USERNAME}:${SUPERUSER_PASSWORD}" "https://${FIRST_NODE_IP_FOR_CLUSTER_INFO}:9200/_cluster/health?pretty")
CLUSTER_NAME=$(echo "$CLUSTER_HEALTH_RESPONSE" | grep '"cluster_name"' | awk -F'"' '{print $4}')

if [ -z "${CLUSTER_NAME}" ]; then
  echo -e "${RED}Could not fetch cluster name from ${FIRST_NODE_IP_FOR_CLUSTER_INFO}. Response:${NC}"
  echo "${CLUSTER_HEALTH_RESPONSE}"
  echo -e "${RED}Please check connectivity, credentials, and if the existing node is healthy. Exiting.${NC}"
  exit 1
fi
echo -e "${GREEN}Detected cluster name: ${CLUSTER_NAME}${NC}"

echo -e "${YELLOW}Configuring Elasticsearch directories and initial yml settings...${NC}"
ES_CONFIG_DIR="/etc/elasticsearch"
ES_DATA_DIR="/var/lib/elasticsearch" # Default path.data
ES_LOG_DIR="/var/log/elasticsearch"   # Default path.logs

sudo mkdir -p "${ES_CONFIG_DIR}/certs" # reconfigure-node will place certs here
sudo mkdir -p "${ES_DATA_DIR}"
sudo mkdir -p "${ES_LOG_DIR}"
sudo chown -R elasticsearch:elasticsearch "${ES_CONFIG_DIR}" "${ES_DATA_DIR}" "${ES_LOG_DIR}"
sudo chmod -R 750 "${ES_CONFIG_DIR}" "${ES_DATA_DIR}" "${ES_LOG_DIR}"

# Create a minimal elasticsearch.yml. elasticsearch-reconfigure-node will populate it.
# It's important that this file exists and is owned by elasticsearch for reconfigure-node.
echo -e "${YELLOW}Writing minimal elasticsearch.yml before reconfiguration...${NC}"
sudo bash -c "cat <<EOF > ${ES_CONFIG_DIR}/elasticsearch.yml
# This file will be mostly overwritten by elasticsearch-reconfigure-node
cluster.name: ${CLUSTER_NAME}
node.name: ${NODE_NAME}
network.host: ${ELASTIC_HOST_IP}
http.port: 9200
path.data: ${ES_DATA_DIR}
path.logs: ${ES_LOG_DIR}

# The following settings related to security and discovery
# will be configured by 'elasticsearch-reconfigure-node'
# xpack.security.enabled: true
# xpack.security.enrollment.enabled: false # This node is joining, not enrolling others initially
# xpack.security.http.ssl.enabled: true
# xpack.security.transport.ssl.enabled: true
# discovery.seed_providers: # Cleared, to be set by reconfigure
# cluster.initial_master_nodes: # Cleared, to be set by reconfigure
EOF"
sudo chown elasticsearch:elasticsearch "${ES_CONFIG_DIR}/elasticsearch.yml"
sudo chmod 660 "${ES_CONFIG_DIR}/elasticsearch.yml" # Writable by elasticsearch group too
echo -e "${GREEN}Minimal elasticsearch.yml written.${NC}"


echo -e "${YELLOW}Joining node to cluster using enrollment token...${NC}"
# This command will reconfigure elasticsearch.yml, set up security, certificates, discovery, etc.
# It needs to be run with sudo as it modifies system files and ES configuration.
progress_bar 15 "Running elasticsearch-reconfigure-node... This may take some time."
if sudo /usr/share/elasticsearch/bin/elasticsearch-reconfigure-node --enrollment-token "${ENROLLMENT_TOKEN}"; then
  echo -e "${GREEN}Node successfully reconfigured and should be ready to join the cluster.${NC}"
else
  echo -e "${RED}elasticsearch-reconfigure-node command failed.${NC}"
  echo -e "${RED}Check the output above for errors. Elasticsearch logs (/var/log/elasticsearch/) may also contain details.${NC}"
  exit 1
fi

# --- Service Management ---
echo -e "${YELLOW}Reloading systemd daemon, enabling and starting Elasticsearch service...${NC}"
sudo systemctl daemon-reload
sudo systemctl enable elasticsearch.service
sudo systemctl start elasticsearch.service
echo -e "${GREEN}Elasticsearch service enabled and start command issued.${NC}"

progress_bar 5 "Waiting for Elasticsearch to initialize (approx. 15-30 seconds)..."
sleep 15

echo -e "${YELLOW}Checking Elasticsearch service status...${NC}"
sudo systemctl status elasticsearch.service --no-pager || true # Display status, continue even if it briefly shows an error

# --- Final Output ---
echo -e "\n${CYAN}======================================================================="
echo -e " Elasticsearch Node ${NODE_NAME} Configuration Complete"
echo -e "=======================================================================${NC}"
echo -e "${GREEN}The node ${NODE_NAME} (${ELASTIC_HOST_IP}) has been configured and started.${NC}"
echo -e "${GREEN}It should now attempt to join the cluster: ${CLUSTER_NAME}.${NC}"
echo -e "${YELLOW}Please monitor the Elasticsearch logs on this node for confirmation of successful joining:${NC}"
echo -e "${YELLOW}  sudo journalctl -u elasticsearch.service -f${NC}"
echo -e "${YELLOW}  sudo cat /var/log/elasticsearch/${CLUSTER_NAME}.log (or similar, log file name might vary slightly)${NC}"
echo -e "${YELLOW}You can also check the cluster status via Kibana Stack Monitoring or by querying an existing node:${NC}"
echo -e "${YELLOW}  curl -k -u <user>:<password> https://${FIRST_NODE_IP_FOR_CLUSTER_INFO}:9200/_cat/nodes?v${NC}"
echo -e "${CYAN}Ensure firewall rules allow communication on ports 9200 (HTTP) and 9300 (Transport) between cluster nodes.${NC}"

exit 0
